use_frameworks!

platform :ios, '9.0'

target 'CrashProtector_Example' do
  pod 'CrashProtector', :path => '../'

  target 'CrashProtector_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
